In [1]:
import pandas as pd
data1 = pd.read_csv("VerizonFinancialsCleaned.csv")
data1.head()

,Date,StockPrice,TTMNetEPS,TTMSalesperShare,PricetoSalesRatio,BookValueperShare,TTMFCFperShare,QuarterlyRevenue,GrossProfit,OperatingIncome,...,CurrentLiailities,CurrentAssetsInventory,QuickRatio,DebtToEquity Ratio,TTMNetIncome,LTInvestmentsDet,TotalAssets,CashOnHand,LongTermDebt,TotalLiabilities
0,6/30/2018,49.73,7.56,31.58,1.57,12.97,6.01,32203,18572,6617,...,32.33,29.77,0.92,2.04,26.40,162.75,263303,1750,109174,209728
1,3/31/2018,46.68,7.63,31.27,1.49,12.67,4.49,31772,18517,7349,...,31.62,29.74,0.94,2.15,27.80,165.08,264516,1923,112734,212171
2,12/31/2017,51.09,7.36,30.83,1.66,10.95,3.57,33955,19535,5230,...,33.04,28.88,0.87,2.54,27.41,158.33,257143,2079,113642,212456
3,9/30/2017,47.20,3.90,30.44,1.55,6.97,3.01,31717,19112,7208,...,28.93,29.59,1.02,4.05,30.21,143.77,254682,4487,115317,226231
4,6/30/2017,42.03,3.90,30.26,1.39,6.56,3.10,30548,18064,8014,...,27.76,27.71,1.00,4.35,29.54,143.15,252978,4583,116390,226217

In [2]:
import numpy as np
# normalize data with natural log of difference between each day, add as extra row
data1['ln StockPrice']=np.log(data1.StockPrice/data1.StockPrice.shift(1))
data1.head()

,Date,StockPrice,TTMNetEPS,TTMSalesperShare,PricetoSalesRatio,BookValueperShare,TTMFCFperShare,QuarterlyRevenue,GrossProfit,OperatingIncome,...,CurrentAssetsInventory,QuickRatio,DebtToEquity Ratio,TTMNetIncome,LTInvestmentsDet,TotalAssets,CashOnHand,LongTermDebt,TotalLiabilities,ln StockPrice
0,6/30/2018,49.73,7.56,31.58,1.57,12.97,6.01,32203,18572,6617,...,29.77,0.92,2.04,26.40,162.75,263303,1750,109174,209728,NaN
1,3/31/2018,46.68,7.63,31.27,1.49,12.67,4.49,31772,18517,7349,...,29.74,0.94,2.15,27.80,165.08,264516,1923,112734,212171,-0.063293
2,12/31/2017,51.09,7.36,30.83,1.66,10.95,3.57,33955,19535,5230,...,28.88,0.87,2.54,27.41,158.33,257143,2079,113642,212456,0.090273
3,9/30/2017,47.20,3.90,30.44,1.55,6.97,3.01,31717,19112,7208,...,29.59,1.02,4.05,30.21,143.77,254682,4487,115317,226231,-0.079195
4,6/30/2017,42.03,3.90,30.26,1.39,6.56,3.10,30548,18064,8014,...,27.71,1.00,4.35,29.54,143.15,252978,4583,116390,226217,-0.116010

In [3]:
#create new dataframe copy the columns and normalize the StockPrice column
data1norm = data1.filter(['Date'], axis=1)
data1norm['StockPrice'] = data1['StockPrice']
data1norm['Log Normal StockPrice']=np.log(data1.StockPrice/data1.StockPrice.shift(1))
data1norm['TTMNetEPS'] = data1['TTMNetEPS']
data1norm['TTMSalesperShare'] = data1['TTMSalesperShare']
data1norm['PricetoSalesRatio'] = data1['PricetoSalesRatio']
data1norm['BookValueperShare'] = data1['BookValueperShare']
data1norm['TTMFCFperShare'] = data1['TTMFCFperShare']
data1norm['QuarterlyRevenue'] = data1['QuarterlyRevenue']
data1norm['GrossProfit'] = data1['GrossProfit']
data1norm['CurrentAssetsInventory'] = data1['CurrentAssetsInventory']
data1norm['OperatingIncome'] = data1['CurrentAssetsInventory']
data1norm['QuickRatio'] = data1['QuickRatio']
data1norm['DebtToEquity Ratio'] = data1['DebtToEquity Ratio']
data1norm['TTMNetIncome'] = data1['TTMNetIncome']
data1norm['LTInvestmentsDet'] = data1['LTInvestmentsDet']
data1norm['TotalAssets'] = data1['TotalAssets']
data1norm['CashOnHand'] = data1['CashOnHand']
data1norm['LongTermDebt'] = data1['LongTermDebt']
data1norm['TotalLiabilities'] = data1['TotalLiabilities']

In [4]:
data1norm.head()

,Date,StockPrice,Log Normal StockPrice,TTMNetEPS,TTMSalesperShare,PricetoSalesRatio,BookValueperShare,TTMFCFperShare,QuarterlyRevenue,GrossProfit,CurrentAssetsInventory,OperatingIncome,QuickRatio,DebtToEquity Ratio,TTMNetIncome,LTInvestmentsDet,TotalAssets,CashOnHand,LongTermDebt,TotalLiabilities
0,6/30/2018,49.73,NaN,7.56,31.58,1.57,12.97,6.01,32203,18572,29.77,29.77,0.92,2.04,26.40,162.75,263303,1750,109174,209728
1,3/31/2018,46.68,-0.063293,7.63,31.27,1.49,12.67,4.49,31772,18517,29.74,29.74,0.94,2.15,27.80,165.08,264516,1923,112734,212171
2,12/31/2017,51.09,0.090273,7.36,30.83,1.66,10.95,3.57,33955,19535,28.88,28.88,0.87,2.54,27.41,158.33,257143,2079,113642,212456
3,9/30/2017,47.20,-0.079195,3.90,30.44,1.55,6.97,3.01,31717,19112,29.59,29.59,1.02,4.05,30.21,143.77,254682,4487,115317,226231
4,6/30/2017,42.03,-0.116010,3.90,30.26,1.39,6.56,3.10,30548,18064,27.71,27.71,1.00,4.35,29.54,143.15,252978,4583,116390,226217

In [5]:
# check for all rows with null values
nan = data1norm[data1norm.isnull().any(axis=1)]
nan

,Date,StockPrice,Log Normal StockPrice,TTMNetEPS,TTMSalesperShare,PricetoSalesRatio,BookValueperShare,TTMFCFperShare,QuarterlyRevenue,GrossProfit,CurrentAssetsInventory,OperatingIncome,QuickRatio,DebtToEquity Ratio,TTMNetIncome,LTInvestmentsDet,TotalAssets,CashOnHand,LongTermDebt,TotalLiabilities
0,6/30/2018,49.73,NaN,7.56,31.58,1.57,12.97,6.01,32203,18572,29.77,29.77,0.92,2.04,26.4,162.75,263303,1750,109174,209728

In [6]:
#drop the first row (make this a loop to drop any null rows)
data1norm.drop(data1norm.index[0])

,Date,StockPrice,Log Normal StockPrice,TTMNetEPS,TTMSalesperShare,PricetoSalesRatio,BookValueperShare,TTMFCFperShare,QuarterlyRevenue,GrossProfit,CurrentAssetsInventory,OperatingIncome,QuickRatio,DebtToEquity Ratio,TTMNetIncome,LTInvestmentsDet,TotalAssets,CashOnHand,LongTermDebt,TotalLiabilities
1,3/31/2018,46.68,-0.063293,7.63,31.27,1.49,12.67,4.49,31772,18517,29.74,29.74,0.94,2.15,27.80,165.08,264516,1923,112734,212171
2,12/31/2017,51.09,0.090273,7.36,30.83,1.66,10.95,3.57,33955,19535,28.88,28.88,0.87,2.54,27.41,158.33,257143,2079,113642,212456
3,9/30/2017,47.20,-0.079195,3.90,30.44,1.55,6.97,3.01,31717,19112,29.59,29.59,1.02,4.05,30.21,143.77,254682,4487,115317,226231
4,6/30/2017,42.03,-0.116010,3.90,30.26,1.39,6.56,3.10,30548,18064,27.71,27.71,1.00,4.35,29.54,143.15,252978,4583,116390,226217
5,3/31/2017,45.34,0.075806,3.00,30.26,1.50,6.14,3.92,29814,17767,25.96,25.96,0.97,4.51,26.08,137.88,246731,4307,112839,221694
6,12/31/2016,49.12,0.080077,3.22,30.84,1.59,5.90,5.34,32340,17978,25.19,25.19,0.83,4.39,27.06,129.47,244180,2880,105433,220148
7,9/30/2016,47.28,-0.038179,3.44,31.29,1.51,5.39,9.13,30937,18708,24.30,24.30,0.80,4.67,28.78,124.72,239498,6441,102739,217515
8,6/30/2016,50.29,0.061719,3.54,31.85,1.58,5.09,11.47,30532,18311,19.91,19.91,0.58,4.48,29.78,113.67,231870,2857,92922,211126
9,3/31/2016,48.20,-0.042447,4.41,32.26,1.49,4.93,12.73,32171,19559,22.47,22.47,0.68,5.15,33.04,123.72,244587,5846,103615,224484
10,12/31/2015,40.69,-0.169377,4.37,32.15,1.27,4.38,13.30,34254,19547,21.10,21.10,0.60,5.79,33.06,121.08,244175,4820,103240,226333
11,9/30/2015,37.81,-0.073409,2.51,32.12,1.18,3.57,11.48,33158,19853,20.45,20.45,0.59,7.23,21.18,119.60,242073,4181,105060,227531
12,6/30/2015,40.04,0.057305,2.41,31.58,1.27,3.17,10.12,32224,19775,20.35,20.35,0.66,8.50,20.54,122.34,240753,3317,109465,227879
13,3/31/2015,41.31,0.031226,2.38,31.27,1.32,2.64,9.01,31984,19888,21.76,21.76,0.76,10.13,20.40,119.71,235790,4933,108949,225031
14,12/31/2014,39.27,-0.050644,2.51,32.50,1.21,3.29,8.30,33192,18789,28.35,28.35,1.01,8.08,19.60,124.21,232616,11153,110536,218940
15,9/30/2014,41.51,0.055473,4.81,34.97,1.19,4.33,12.65,31586,19334,23.57,23.57,0.88,5.99,33.80,125.60,226293,7853,107627,208325
16,6/30/2014,40.19,-0.032316,4.70,37.91,1.06,3.86,15.89,31483,19396,21.81,21.81,0.82,6.73,34.04,123.71,224427,6424,107696,208415
17,3/31/2014,38.65,-0.039071,4.47,40.70,0.95,3.34,17.69,30818,19629,22.39,22.39,0.88,7.77,32.91,121.47,221562,3544,107617,207711
18,12/31/2013,39.49,0.021501,4.00,41.96,0.94,33.34,18.19,31065,19103,69.97,69.97,2.59,0.94,31.97,185.07,274098,54129,89658,178682
19,9/30/2013,37.08,-0.062970,0.76,41.65,0.89,31.54,15.81,30279,19319,72.51,72.51,2.39,1.01,16.74,181.20,276675,57341,90938,186410
20,6/30/2013,39.60,0.065751,0.54,41.23,0.96,30.46,14.73,29786,18753,20.92,20.92,0.72,0.48,15.09,128.95,223346,2406,41791,136190
21,3/31/2013,38.26,-0.034424,0.40,40.85,0.94,30.61,14.15,29420,18488,24.46,24.46,0.78,0.48,14.19,129.58,226186,6135,41993,138598
22,12/31/2012,33.29,-0.139148,0.31,40.52,0.82,29.92,13.62,30045,16976,20.16,20.16,0.75,0.56,13.16,133.15,225222,3563,47618,139689
23,9/30/2012,34.68,0.040906,1.08,40.04,0.87,32.46,13.04,29007,18016,26.44,26.44,0.92,0.50,15.22,139.10,231082,10307,46467,138454
24,6/30/2012,33.44,-0.036410,1.01,39.75,0.84,31.74,11.51,28552,17656,26.27,26.27,1.00,0.51,14.38,136.91,226072,10778,46479,135644
25,3/31/2012,28.39,-0.163716,0.94,39.46,0.72,31.12,10.13,28242,16923,22.45,22.45,0.98,0.55,13.62,136.90,222921,6532,48476,134500
26,12/31/2011,29.41,0.035298,0.86,39.07,0.75,30.31,9.53,28436,16346,30.00,30.00,0.98,0.59,12.88,136.21,230461,13954,50303,144553
27,9/30/2011,26.60,-0.100424,2.50,38.38,0.69,30.91,10.73,27913,16515,26.62,26.62,0.77,0.53,20.40,133.80,228032,10858,46285,140517
28,6/30/2011,26.57,-0.001128,2.32,37.90,0.70,32.05,12.29,27536,16378,21.20,21.20,0.78,0.53,19.14,138.64,223756,6828,47927,133044
29,3/31/2011,27.16,0.021963,1.68,37.67,0.72,31.41,14.18,26990,15761,28.68,28.68,0.88,0.56,14.66,138.24,228108,14730,49374,139244
30,12/31/2010,24.88,-0.087681,1.31,37.63,0.66,30.74,15.23,26395,15785,21.22,21.22,0.69,0.52,14.65,132.16,220005,7213,45252,133093
31,9/30/2010,22.33,-0.108133,0.15,37.85,0.59,29.94,14.38,26484,15813,20.33,20.33,0.71,0.56,11.11,131.98,220852,5975,47360,136228
32,6/30/2010,17.65,-0.235195,0.25,38.09,0.46,29.88,13.41,26773,14557,20.08,20.08,0.63,0.59,11.72,134.07,226251,5225,49594,141778
33,3/31/2010,19.24,0.086256,0.84,38.07,0.51,29.95,12.28,26913,16261,21.29,21.29,0.76,0.64,15.73,139.08,227347,3557,54424,142695
34,12/31/2009,20.24,0.050669,1.28,37.95,0.53,29.67,12.02,27091,14297,20.32,20.32,0.70,0.65,15.98,139.19,226907,2499,55051,142764
35,9/30/2009,18.20,-0.106239,1.94,37.06,0.49,29.78,10.53,27265,16269,19.47,19.47,0.71,0.68,2.66,141.96,226404,1690,57374,141822
36,6/30/2009,18.19,-0.000550,2.12,36.17,0.50,29.16,9.36,26861,16380,18.69,18.69,0.71,0.72,2.85,142.29,224999,1180,59469,142178
37,3/31/2009,17.62,-0.031837,2.26,35.17,0.50,28.36,8.72,26591,16283,19.68,19.68,0.56,0.69,2.97,136.23,226851,4351,55674,146297
38,12/31/2008,19.49,0.100867,2.25,34.13,0.57,27.78,8.10,24645,15061,23.98,23.98,0.93,0.60,2.61,125.86,202352,10291,46959,123447
39,9/30/2008,18.15,-0.071231,2.19,33.70,0.54,17.94,7.69,24752,14704,16.65,16.65,0.59,0.74,16.48,88.43,204861,1674,37478,153907
40,6/30/2008,19.78,0.086001,2.04,33.19,0.60,17.87,6.71,24124,14658,15.78,15.78,0.53,0.66,16.51,84.67,200646,2074,33778,149759
41,3/31/2008,20.04,0.013059,1.96,32.74,0.61,17.64,6.07,23833,14316,20.78,20.78,0.84,0.64,16.12,82.41,191293,7442,32134,141013
42,12/31/2007,23.78,0.171115,1.90,32.18,0.74,17.58,5.78,23840,14044,16.97,16.97,0.69,0.56,15.58,78.78,186959,3397,28203,136378
43,9/30/2007,23.88,0.004196,1.88,31.66,0.75,17.19,4.96,23772,14164,15.25,15.25,0.63,0.59,15.60,79.07,185619,1909,29383,135930
44,6/30/2007,21.98,-0.082908,2.10,31.14,0.71,17.17,5.41,23273,14042,15.24,15.24,0.62,0.59,14.93,79.21,184760,2356,29374,134929
45,3/31/2007,20.04,-0.092403,2.07,30.56,0.66,16.80,5.66,22584,13672,16.11,16.11,0.58,0.58,13.99,76.86,184284,3450,28073,135502
46,12/31/2006,19.46,-0.029369,2.12,29.96,0.65,16.67,6.23,22606,13454,21.02,21.02,0.65,0.59,13.37,77.18,188804,5653,28646,140269

In [7]:
#create new dataframe for ratios
data1ratios = data1norm.filter(['Date'], axis=1)

#caclulate the ratios and make sure they match
#PE Ratio = StockPrice/TTMNetEPS
#data1ratios['PE Ratio'] = data1['PE Ratio']
data1ratios['PE Ratio Calculated'] = (data1norm['StockPrice']/data1norm['TTMNetEPS']) #should we trim these?

#Current Ratio = TotalAssets/TotalLiabilities
data1ratios['Current Ratio Calculated'] = (data1norm['TotalAssets']/data1norm['TotalLiabilities'])

data1ratios.head()
#then combine all preproccessed data to a final data frame
#then export to csv

         Date  PE Ratio Calculated  Current Ratio Calculated
0   6/30/2018             6.578042                  1.255450
1   3/31/2018             6.117955                  1.246711
2  12/31/2017             6.941576                  1.210335
3   9/30/2017            12.102564                  1.125761
4   6/30/2017            10.776923                  1.118298